default_language_version:
    python: python3.10.13

fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Google, -i]
      - id: clang-tidy
#      - id: oclint
#      - id: uncrustify
#      - id: cppcheck
#      - id: cpplint
      - id: include-what-you-use
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace      # trims trailing whitespace.
    -   id: end-of-file-fixer  	     # ensures that a file is either empty, or ends with one newline.
    -   id: check-yaml         	     # checks yaml files for parseable syntax.
    -   id: check-added-large-files  # prevents giant files from being committed.
    -   id: check-merge-conflict     # checks for files that contain merge conflict strings.
    -   id: check-toml               # checks for files that contain merge conflict strings.
    -   id: sort-simple-yaml	     # checks for files that contain merge conflict strings.
    -   id: check-case-conflict	     # checks for files that would conflict in case-insensitive filesystems.

# mypy i.e. type checking. Checks with --ignore-missing-imports for technical reasons
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [types-toml==0.10.8.7]

# pygrep-hooks. Checks for type stuff
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations  #  Enforce that python3.6+ type annotations are used instead of type comments
    -   id: python-check-blanket-noqa    # Enforce that noqa annotations always occur with specific codes. Sample annotations: # noqa: F401, # noqa: F401,W203
