name: fastsum
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.13
  - numpy=1.25.2
  - matplotlib=3.7.2                 # Plots
#  - pandas=2.0.3                     # CSV read/write mostly
  - typing=3.10.0.0                  # type-hints
#  - scipy=1.11.1
  - pip=23.2.1
  - mypy=0.981                       # some type/syntax checking
#  - sympy=1.11.1                     # For arbitrary maths of input correlators mostly
#  - toml=0.10.2                      # Input files
#  - poppler=22.12.0                  # latex strings
#  - opt_einsum=3.3.0                 # for doing einsum with gvar objects
#  - cython=0.29.35                   # This and gvar have specific versions for compat. reasons.
#                                     # This may be fixed in newer versions of gvar
#  - pygments=2.15.1		     # For the minted package to display code in tex
  - conda-forge::pre-commit=3.4.0    # For forcing formatting ,etc
                                     # comment these if you want to use your own gxx and gfortran
  - conda-forge::gxx                 # for cppyy on weird machines without g++
  - conda-forge::gfortran            # gfortran for weird machines without it
#  - conda-forge::findiff=0.10.0      # finite difference derivatives in any number of dimensions.
  - conda-forge::clang-format        # for clang-format
  - conda-forge::clang-tools         # for clang-tidy
  - conda-forge::uncrustify          # uncrustify
  - conda-forge::include-what-you-use # similarly
  - pip:
#     - lsqfit==13.0.1                # Fits gvar variables
#     - gvar==11.11.13                # Specific version for compat. with cython
#                                     # Gaussian tracking of errors
     - types-toml==0.10.8.7          # Gets more types workinig
     - lyncs_io                      # for io of gaugefields
     - lyncs_cppyy                   # required for loading openqcd format
     - cpplint                       # linter for cpp
